### ISSUE TITLE
Virtualize list of rule and release revisions

### ISSUE THREAD

**Issue by helfi92** [mozilla-frontend-infra/balrog-ui#104]
Reference: https://github.com/mozilla-frontend-infra/balrog-ui/pull/102#issuecomment-513885645

Solution: Use https://github.com/bvaughn/react-virtualized

**Comment by helfi92** [comment]
@mozbhearsum I was wondering if we ever need more than the last 50 revisions of a rule or release. Virtualization may not be needed after all.

**Comment by mozbhearsum** [comment]
For Rules it's certainly rare (but occasionally needed). For releases it's much more common to need to dig back hundreds, or even more than a thousand revisions back.

**Comment by helfi92** [comment]
Gotcha. Let's virtualize :)

**Comment by helfi92** [comment]
We should be able to copy-paste some of the logic in https://github.com/mozilla-frontend-infra/balrog-ui/pull/137 to virtualize the rules list. I can do that once #137 is merged.
