### ISSUE TITLE
Do something with the index page

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-frontend-infra/balrog-ui#111]
Right now it just says "Home". A very simple thing we could do is provide links to common filters of the Rules page. Eg: Firefox release channel and some others.

Something even nicer would be #88, but that may be a lot more work.

**Comment by helfi92** [comment]
> A very simple thing we could do is provide links to common filters of the Rules page. Eg: Firefox release channel and some others.

That's a really good idea! We do something similar in Taskcluster UI:

### Logged out

![Screen Shot 2019-07-24 at 9 59 16 AM](https://user-images.githubusercontent.com/3766511/61799820-cbd97980-adf9-11e9-8a52-36b7893d72cb.png)


### Logged in

![Screen Shot 2019-07-24 at 9 58 06 AM](https://user-images.githubusercontent.com/3766511/61799740-a6e50680-adf9-11e9-93ad-125885f0b726.png)

**Comment by helfi92** [comment]
![Screen Shot 2019-08-12 at 5 04 31 PM](https://user-images.githubusercontent.com/3766511/62898369-4cb5d200-bd23-11e9-9c6d-b75e57883516.png)
