### ISSUE TITLE
Sort list of suggestions that AutoCompleteText receives

### ISSUE THREAD

**Issue by helfi92** [mozilla-frontend-infra/balrog-ui#124]
Let's sort the list of suggestions that the AutoCompleteText component receives with `useMemo`.

Idea came from https://github.com/mozilla-frontend-infra/balrog-ui/pull/123#discussion_r308227550.

**Comment by divyanshu-rawat** [comment]
Hey, @helfi92 can I work on this issue? 😅

**Comment by helfi92** [comment]
👋 It's all yours :-)

**Comment by divyanshu-rawat** [comment]
@helfi92 as per your conversation in #123 you mentioned. 

`I think it's best to do it in the component that uses it so that we can use useMemo to memoize the list and avoid having to sort the list on each render. I'll file an issue for that.`

So, where exactly do we need to sort the list?

**Comment by helfi92** [comment]
We'll want to sort the list of input we feed to all of the AutoCompleteText getSuggestions props. For example,

https://github.com/mozilla-frontend-infra/balrog-ui/blob/4a785fb895d97951d5379de47458152a4f23dbb2/src/views/Users/ViewUser/index.jsx#L382

would become:

```jsx
getSuggestions={getSuggestions(ALL_PERMISSIONS.sort())} 
```

**Comment by divyanshu-rawat** [comment]
@helfi92 I am getting this err. `Error contacting Balrog backend: Error: Network Error. Are you connected to the VPN?` I tried the same by connecting with one VPN but then it said VPN is disabled for this site, do you know any work around so that I can proceed 👍

**Comment by mozbhearsum** [comment]
> @helfi92 I am getting this err. `Error contacting Balrog backend: Error: Network Error. Are you connected to the VPN?` I tried the same by connecting with one VPN but then it said `VPN is disabled for this site`, do you know any work around so that I can proceed +1

You'll need to also have the primary Balrog application running for the UI to work. You can do that by running `docker-compose up` after cloning https://github.com/mozilla/balrog.

(The VPN mentioned in the error message is the Mozilla VPN that our production instance sits behind.)

**Comment by divyanshu-rawat** [comment]
cool @mozbhearsum 👍

**Comment by divyanshu-rawat** [comment]
@mozbhearsum Here the connections requests after running `docker-compose up` , barlog admin at` localhost:9000` throws same warning of not connected to VPN, even if I try to login its the same.

<img width="1563" alt="Screenshot 2019-12-17 at 21 42 54" src="https://user-images.githubusercontent.com/13464678/71032859-8144fa80-2116-11ea-878c-1150b62af66a.png">
