### ISSUE TITLE
diff viewer missing style in production builds

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-frontend-infra/balrog-ui#130]
![image](https://user-images.githubusercontent.com/49649/62305136-5733ba00-b44d-11e9-94c5-ba21e43eef36.png)

(The style is also missing on ListRuleRevisions.)

I think this is related to moving the diff viewer to its own component in https://github.com/mozilla-frontend-infra/balrog-ui/commit/073017948ac867af156fba45bc8813162f75d1ec#diff-a0795e915062262d1dae44d4335bf63c. I tried moving the `import 'react-diff-view/style/index.css';` line to the DiffRule component (and a few other places), but that didn't help.

**Comment by helfi92** [comment]
Wow. What's would be the best way to replicate this issue?

**Comment by mozbhearsum** [comment]
> Wow. What's would be the best way to replicate this issue?

If https://balrog-admin-static-stage.stage.mozaws.net/ works for you, that should do it. If it doesn't, we can either get you access to it (will take some time), or you can serve the build site with a local web server to repro (that's how I was testing my potential fixes).

**Comment by helfi92** [comment]
@mozbhearsum Could you check if you are still able to replicate the issue on latest master, please?

**Comment by mozbhearsum** [comment]
It looks fixed to me after pulling in the updated `react-diff-view`.
