### ISSUE TITLE
yarn install throws with node 12

### ISSUE THREAD

**Issue by helfi92** [mozilla-frontend-infra/balrog-ui#139]
From IRC:

> fyi, I had to pin fsevents to 1.2.9 so that yarn+node12 could setup the new ui

Possible fix: Lock the version of node using https://docs.npmjs.com/files/package.json#engines until there is a better solution than pining fsevents to 1.2.9.

**Comment by mozbhearsum** [comment]
Let's be sure to update https://github.com/mozilla-frontend-infra/balrog-ui/blob/master/docker-compose.yml#L7 to use node10 if we lock the node version.
