### ISSUE TITLE
allow scheduled changes to be cancelled

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-frontend-infra/balrog-ui#141]
We sortof support this in Required Signoffs, which will delete scheduled changes if you revert values back to their original form, but in other parts of the UI this technique is more painful. Eg: you don't want to force a user to copy a bunch of Rule fields to their original value, detect that, and cancel a scheduled change. We also need to allow scheduled deletions/inserts to be cancelled, which don't work at all with that technique.

In the old UI, we have a "Delete Scheduled Change" button in the modal edit dialog. In this UI, we could it on the edit pages and/or the primary UI. I'm not sure which makes the most sense.

**Comment by helfi92** [comment]
Is "Delete Scheduled Change" different than "Cancel Pending Change" from the new UI?

![Screen Shot 2019-08-08 at 5 32 22 PM](https://user-images.githubusercontent.com/3766511/62739390-ac01a280-ba02-11e9-9902-e5f000d23c6b.png)

**Comment by mozbhearsum** [comment]
Hm, no. I totally forgot that we had that! I think we may need to add it to some other parts of the UI, though. Eg: it's not possible to cancel pending changes to user permissions at the moment.

**Comment by helfi92** [comment]
> I think we may need to add it to some other parts of the UI

Sounds good to me. What views did you have in mind? We should track this somewhere (here?) :)

**Comment by mozbhearsum** [comment]
> Sounds good to me. What views did you have in mind? We should track this somewhere (here?) :)

Yeah, I was thinking here. I'll take a look and see exactly where we need to add support.

**Comment by mozbhearsum** [comment]
Hm! So it turns out that I'm wrong. Both the Users and Required Signoffs views will cancel scheduled changes if they're reverted in the edit view. This means that the only place we need this is the yet-to-be-implemented Releases view (#59). We can probably use a "Cancel" button in the edit view like we did for Rules for this.
