### ISSUE TITLE
Users page not showing product or action restrictions

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-frontend-infra/balrog-ui#143]
I tried debugging this a bit and as far as I can tell, both the `actions` and `products` lists for permissions end up as empty. I tried to figure out when this regressed, but it turns out that ever since the first version of `ListUsers` landed, this has been a problem -- it just doesn't occur until the second render (which didn't happen unless a hotreload came in until recently).

It seems like there's something changing `users` after the render caused by https://github.com/mozilla-frontend-infra/balrog-ui/blob/344d2d2017e2c10c3b0a4ea7569c468eebd788ee/src/views/Users/ListUsers/index.jsx#L77. I tried tracing this in a bunch of ways, but couldn't figure it out. My best guess is that something funky is going on in `getUsersInfo` or `UserCard`, but nothing I've tried uncovers or fixes it.

**Comment by helfi92** [comment]
I think https://github.com/mozilla-frontend-infra/balrog-ui/pull/144 was the fix.
