### ISSUE TITLE
token refresh not happening on page reload

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-frontend-infra/balrog-ui#183]
I'm running the latest master (+ a few unrelated changes) locally and at some point my token expired, did not refresh itself, and is not refreshing itself on page reload.

I'm not sure how to debug this myself, but here's my current session:
`{"authResult":{"accessToken":"[redacted]","idTokenPayload":{"nickname":"mozbhearsum","name":"Ben Hearsum","picture":"https://avatars0.githubusercontent.com/u/49649?v=4","updated_at":"2019-08-27T19:28:41.374Z","email":"bhearsum@mozilla.com","email_verified":true,"iss":"https://balrog-localdev.auth0.com/","sub":"github|49649","aud":"GlZhJQfx52b7MLQ19AjuTJHieiB4oh1j","iat":1567188176,"exp":1567195376,"at_hash":"qJ6zDExas3haxiBbW5z6_g","nonce":"[redacted]"},"appState":"NzO1rr0B~~~K40ZIopt23N4S99B58-Ka","refreshToken":null,"state":"NzO1rr0B~~~K40ZIopt23N4S99B58-Ka","expiresIn":7198,"tokenType":"Bearer","scope":"openid profile email"},"userInfo":{"sub":"github|49649","nickname":"mozbhearsum","name":"Ben Hearsum","picture":"https://avatars0.githubusercontent.com/u/49649?v=4","updated_at":"2019-08-27T19:28:41.374Z","email":"bhearsum@mozilla.com","email_verified":true},"expiration":"2019-08-30T22:06:41.031Z"}`

On refresh, no attempt is made to contact auth0.

I'm guessing this is because the expiration is claimed to be `2019-08-30T22:06:41.031Z`, but as of this writing, we're ~2h away from that.

**Comment by helfi92** [comment]
> and at some point my token expired, did not refresh itself, and is not refreshing itself on page reload

If a token expires, it won't be able to refresh itself. In order to refresh a token, I think the current token needs to be valid. One thing we can probably do is add a [`leeway`](https://github.com/mozilla-frontend-infra/react-auth0-components/blob/20626c167ba28e3b4ada75825630449651a0ce60/src/components/Authorize/index.jsx#L108-L112) to refresh a bit in advance `<Authorize leeway={10} ... />  `

**Comment by mozbhearsum** [comment]
That seems like a good idea. I'll make a PR.
