### ISSUE TITLE
Add Edit/Create Rule Layout

### ISSUE THREAD

**Issue by helfi92** [mozilla-frontend-infra/balrog-ui#19]
Once https://github.com/mozilla-frontend-infra/balrog-ui/pull/15 is merged, navigating to `/rules` shows:

![Screen Shot 2019-06-03 at 11 10 56 AM](https://user-images.githubusercontent.com/3766511/58812695-5ec31800-85f0-11e9-918b-8f127ae02cf6.png)

Clicking the "Update" on a rule should navigate the user to the rule form with prefilled entries. Clicking on the "+" button on the other hand should navigate the user to the same view but with an empty form. The form should also allow users to schedule an update/creation.

**Comment by helfi92** [comment]
@mozbhearsum What makes a rule unique? I'm asking to see how should the URL look like when a user clicks on "Update".

**Comment by mozbhearsum** [comment]
> @mozbhearsum What makes a rule unique? I'm asking to see how should the URL look like when a user clicks on "Update".

`rule_id` or `alias` is the unique identifier for a Rule, and both are accepted by the Rules endpoints.

We'll also need:
* A way to schedule the creation of a new Rule
* A way to Schedule a Change for a Rule
* A way to edit an existing Scheduled Change for a Rule

These forms are almost identical to the add/edit form, except that they also should have a Datetime control to select when the change should be enacted. I wonder if they can use the same view, with a toggle for whether you're doing a direct update or scheduling a change?

Also, if the Rule's product/channel has Required Signoffs, only Scheduled Changes may be used to alter them (direct updates will fail when sent to the backend).

And while not strictly necessary, having a "Duplicate" button that creates a new Rule or Scheduled Change prefilled with the data from another Rule is very helpful.

**Comment by helfi92** [comment]
Perfect, thank you for elaborating!

**Comment by helfi92** [comment]
I'm having trouble retrieving a response when requesting the schedule change of an individual resource. For example, when I try `https://localhost:8010/api/scheduled_changes/rules/195` I get a `405` with  an error message `The method is not allowed for the requested URL.`. I wonder if this is a bug.

**Comment by mozbhearsum** [comment]
> I'm having trouble retrieving a response when requesting the schedule change of an individual resource. For example, when I try `https://localhost:8010/api/scheduled_changes/rules/195` I get a `405` with an error message `The method is not allowed for the requested URL.`. I wonder if this is a bug.

We actually never had a need to implement that. The old UI simply uses `/scheduled_changes/rules` to retrieve all of the scheduled changes. We can add it if you need it, though.

**Comment by helfi92** [comment]
How complicated is it to add it? It would definitely be a nice to have. I actually got this endpoint url from https://github.com/mozilla/balrog/blob/695f19fa6b7167b2b27beb65d3bfae5a21ff32dc/ui/app/js/services/rules_service.js#L49-L51.

**Comment by mozbhearsum** [comment]
> How complicated is it to add it? It would definitely be a nice to have. I actually got this endpoint url from https://github.com/mozilla/balrog/blob/695f19fa6b7167b2b27beb65d3bfae5a21ff32dc/ui/app/js/services/rules_service.js#L49-L51.

Well that's funny. That method exists, but is never called (and I doubled checked - the endpoint doesn't exist on the server).

It's not tough to add, I'll get a patch together. Now that we have a view that just wants a single scheduled change, it seems pretty important to have.

**Comment by helfi92** [comment]
Agreed. Thanks @mozbhearsum!

**Comment by helfi92** [comment]
Merged in https://github.com/mozilla-frontend-infra/balrog-ui/commit/2850b7089d704ff398660fa61c93368d234a5096.
