### ISSUE TITLE
Updating a rule OS version text field

### ISSUE THREAD

**Issue by helfi92** [mozilla-frontend-infra/balrog-ui#192]
<img width="463" alt="Screen Shot 2019-09-05 at 12 01 05 PM" src="https://user-images.githubusercontent.com/3766511/64358693-ee53da80-cfd4-11e9-820b-c62f8e199db3.png">

It would be nice to have the OS version displayed in a multi-line text-field to improve readability.

**Comment by mozbhearsum** [comment]
:+1: 

I think folks were also hoping that we could wrap the multiline OS Version in Rules such as:
![image](https://user-images.githubusercontent.com/49649/64378822-8b296e80-cffb-11e9-811c-3edacfc96e65.png)
