### ISSUE TITLE
 Sort rules using priority after scheduled changes ?

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-frontend-infra/balrog-ui#196]
Tom had some Thunderbird changes scheduled, including an increase to priority on one rule (see screenshot). The rules list remained sorted by the current priorities rather than the future ones. In this particular case it would have been helpful to see rule 632 above rule 14.

https://bugzilla.mozilla.org/attachment.cgi?id=8922086

(Imported from https://bugzilla.mozilla.org/show_bug.cgi?id=1411759)

**Comment by helfi92** [comment]
When a scheduled change happens, we show a red dot beside changed properties and also show the diff

<img width="892" alt="Screen Shot 2019-09-06 at 4 20 15 PM" src="https://user-images.githubusercontent.com/3766511/64458057-53392e80-d0c2-11e9-9757-41e71bb8f750.png">

The list should get re-ordered once the backend implements the signoffs. The one from the picture doesn't seem to require signoffs though. How long does it take for the backend to update the data?

**Comment by mozbhearsum** [comment]
We check for ready scheduled change every 30 seconds. If that wasn't getting enacted, your local Agent may not have been running.

However, the original bug is wondering whether or not Scheduled Change priority should be the default sort. ie: is it more useful to users to have it sorted that way, rather than by current priority. I believe the thinking is that usually when we're browsing Rules with Scheduled Changes, we're trying to verify that they look correct, in which case sorting by Scheduled Change priority may make more sense.

(ccing @nthomas-mozilla since he filed this originally)

**Comment by helfi92** [comment]
>  I believe the thinking is that usually when we're browsing Rules with Scheduled Changes, we're trying to verify that they look correct

Ah, I see. I think the red dot in the new UI should help a bit.

**Comment by mozbhearsum** [comment]
We were making a number of priority changes to some Rules today and I'm pretty convinced that sorting on the new priority would be a good idea - it was pretty difficult to reason about the Rules because I couldn't simply scroll and see the proposed new order of them.

I'm not sure what do with the `priority` number if we do this, though. Do we display the scheduled change's priority with the red dot, and still show the diff? Or do we show the old and new priority somehow? Something else?

**Comment by nthomas-mozilla** [comment]
> We were making a number of priority changes to some Rules today and I'm pretty convinced that sorting on the new priority would be a good idea - it was pretty difficult to reason about the Rules because I couldn't simply scroll and see the proposed new order of them.

👍  

> I'm not sure what do with the `priority` number if we do this, though. Do we display the scheduled change's priority with the red dot, and still show the diff? 

I'm fine with this solution.

**Comment by mozbhearsum** [comment]
This was fixed in #207
