### ISSUE TITLE
Make RuleCard's a bit more dense

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-frontend-infra/balrog-ui#206]
Follow-up with a bit more from #149 @helfi92 has some more ideas about how to do this.

**Comment by rbrishabh** [comment]
Hey @helfi92 ! If you want, I can take this up! You can just let me know how you'd like RuleCard's to look like!

**Comment by helfi92** [comment]
Hi @rbrishabh. This issue is already assigned and may not be the best "good-first-issue". Do you want to look at something like https://github.com/mozilla-frontend-infra/balrog-ui/issues/197 instead? I think it could be an interesting task :-)

**Comment by rbrishabh** [comment]
Sure! :D
