### ISSUE TITLE
[staging] Revisions of a release don't show up

### ISSUE THREAD

**Issue by nthomas-mozilla** [mozilla-frontend-infra/balrog-ui#208]
If I load [Firefox-71.0b1-build1 release in stage](https://balrog-admin-static-stage.stage.mozaws.net/releases/Firefox-71.0b1-build1/revisions) the page doesn't show any history. The request seems to go to the prod bucket instead of stage:
https://www.googleapis.com/storage/v1/b/balrog-prod-release-history-v1/o?prefix=Firefox-71.0b1-build1/&delimeter=/

**Comment by mozbhearsum** [comment]
Hm, indeed. It looks like we're hardcoding it in https://github.com/mozilla/balrog/blob/master/react-ui/.neutrinorc.js#L64 and not overwriting it in the stage config...

**Comment by mozbhearsum** [comment]
Fixed this by updating the stage config and redeploying.
