### ISSUE TITLE
consider a dedicated download button for Balrog releases page

### ISSUE THREAD

**Issue by lundjordan** [mozilla-frontend-infra/balrog-ui#216]
This was available on the old UI and is handy when needing to edit a release blob.

I tried hitting "update" then copy/pasting the json from within the text box but on my mac, <command>a to select and then <command>c to copy did not work in FF. The only other option is to select text with mouse and drag to bottom. This would take minutes to do with big release blobs and without tweaking scroll speed.

**Comment by helfi92** [comment]
I can replicate on a release that is "Read-Only". Otherwise, "Command+A" works for me on a mac in FF.

**Comment by lundjordan** [comment]
thanks for testing. maybe that was it. I was trying to copy the main ff release official rule which was probably read-only.

also, I neglected to release that github's markdown would scrub me writing "\< command \> a". Sounds like you figured it out.

**Comment by helfi92** [comment]
Resolved in https://github.com/mozilla-frontend-infra/balrog-ui/commit/03121e5f464a80da43e3c7475db0e29c0ca6cafc.

**Comment by lundjordan** [comment]
wfm. thanks!
