### ISSUE TITLE
consider a dedicated `upload` button for Balrog release blobs

### ISSUE THREAD

**Issue by lundjordan** [mozilla-frontend-infra/balrog-ui#217]
when creating a new or updating a release

benefits of old UI

1) can locally edit json
2) when uploading, json was validated (can be solved outside of that I suppose)
3) the Balrog name was auto scraped and populated from the json when uploading

**Comment by mozbhearsum** [comment]
It's worth noting that these two things could be solved in other ways:

>     2. when uploading, json was validated (can be solved outside of that I suppose)

I'm not sure how expensive it would be on large blobs, but it's certainly possible to do JSON validation as-you-edit.

>     3. the Balrog name was auto scraped and populated from the json when uploading

Syncing the `name` field from within the JSON to the `name` field outside of it should be trivial.

That's not to say it's not worth doing an upload button instead or in addition to the above, though.
