### ISSUE TITLE
Enhance button component

### ISSUE THREAD

**Issue by helfi92** [mozilla-frontend-infra/balrog-ui#25]
Idea: Allow a button to be disabled when we know that button requires a user to be authenticated (e.g., triggering a protected request). Something similar to https://taskcluster-ui.herokuapp.com/secrets/create

![Screen Shot 2019-06-06 at 11 46 32 AM](https://user-images.githubusercontent.com/3766511/59046870-c8416180-8850-11e9-800f-682c1978392d.png)

The logic will be similar to https://github.com/taskcluster/taskcluster/blob/master/ui/src/components/Button/index.jsx.

@mozbhearsum Thoughts?

**Comment by mozbhearsum** [comment]
Is this still useful if we're hiding the Settings button and/or booting non-logged in users from those pages?

**Comment by helfi92** [comment]
Probably not if we're booting them :) Closing as WONTFIX.
