### ISSUE TITLE
Error when loading Firefox release channel rules

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-frontend-infra/balrog-ui#26]
```
Warning: Failed prop type: Invalid prop `secondary` supplied to `ForwardRef(ListItemText)`, expected a ReactNode.
```

It looks like this is related to the mig64 field, and possibly only happens when it is not null.

**Comment by helfi92** [comment]
I can't seem to replicate. Am I looking at the wrong view by any chance?

<img width="1594" alt="Screen Shot 2019-06-16 at 9 43 43 AM" src="https://user-images.githubusercontent.com/3766511/59566914-6d6bef00-9034-11e9-8959-11d932f23022.png">

**Comment by mozbhearsum** [comment]
Possibly - try loading the Firefox release channel rules. They definitely have `mig64` in some rules.

**Comment by mozbhearsum** [comment]
Eg: http://localhost:9000/rules?product=Firefox&channel=release

**Comment by helfi92** [comment]
Thanks for the link. I can replicate. Sending a fix now.
