### ISSUE TITLE
Deep links to /users/:username don't work if the username contains an @

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-frontend-infra/balrog-ui#28]
Eg, works fine for http://localhost:9000/users/balrogagent but not http://localhost:9000/users/bhearsum@mozilla.com. The latter gives me a white page with `Cannot GET /users/bhearsum@mozilla.com`

**Comment by helfi92** [comment]
Ah, that's because dots in URLs are disabled by default with Webpack. I've created a pull-request to fix that.
