### ISSUE TITLE
Requests with access token fail (regression?)

### ISSUE THREAD

**Issue by helfi92** [mozilla-frontend-infra/balrog-ui#30]
STR:

1. Navigate to http://localhost:9000/required-signoffs
2. Log in
3. Refresh the page

Actual: "Network Error"
Expected: The UI shows a list of required signoffs

**Comment by helfi92** [comment]
@mozbhearsum Any idea why requests fail when an access token is attached?

**Comment by mozbhearsum** [comment]
Can you see what the developer toolbar says about the request? In most cases that I've seen that, it's because I forgot to start Balrog itself.

**Comment by helfi92** [comment]
Here's a screenshot of the developer toolbar:

<img width="1676" alt="Screen Shot 2019-06-18 at 8 33 04 AM" src="https://user-images.githubusercontent.com/3766511/59698054-e5fdb780-91bc-11e9-9ffb-f5cee6e14d55.png">

>  In most cases that I've seen that, it's because I forgot to start Balrog itself.

fwiw, when the user is not logged in, the response returns a list.

**Comment by mozbhearsum** [comment]
I think we determined that this was an issue with the Balrog backend code you were running?

**Comment by helfi92** [comment]
Right. The `kill-csrf` branch was the fix.
