### ISSUE TITLE
Retrieving the scheduled change for a rule

### ISSUE THREAD

**Issue by helfi92** [mozilla-frontend-infra/balrog-ui#35]
From https://github.com/mozilla-frontend-infra/balrog-ui/issues/19#issuecomment-506391229:

I'm having trouble retrieving a response when requesting the schedule change of an individual resource. For example, when I try https://localhost:8010/api/scheduled_changes/rules/195 I get a 405 with an error message The method is not allowed for the requested URL.. I wonder if this is a bug.

**Comment by helfi92** [comment]
**TODO** once this issue is resolved:

* [ ] Only allow modifying the scheduled time when updating a rule with a scheduled change
* [ ] Add button to a delete scheduled change when updating a rule with a scheduled change

Question: When a user deletes a rule with a schedule change, is the deletion scheduled or does it happen instantly?

**Comment by mozbhearsum** [comment]
> **TODO** once this issue is resolved:
> 
>     * [ ]  Only allow modifying the scheduled time when updating a rule with a scheduled change
> 
>     * [ ]  Add button to a delete scheduled change when updating a rule with a scheduled change
> 
> 
> Question: When a user deletes a rule with a schedule change, is the deletion scheduled or does it happen instantly?

Do you mean a direct delete of the Rule, or deleting a Rule via a scheduled change?

**Comment by helfi92** [comment]
I'm referring to the "Delete Scheduled Change".

![Screen Shot 2019-06-27 at 1 24 52 PM](https://user-images.githubusercontent.com/3766511/60287059-fb6e9200-98de-11e9-967b-d70033b848b9.png)

**Comment by helfi92** [comment]
Never mind I think I get it. The "Delete Scheduled Change" button in the pop-up is the same as the "Schedule For Deletion" button that we see in the rules view.

![Screen Shot 2019-06-27 at 1 32 01 PM](https://user-images.githubusercontent.com/3766511/60287471-f9590300-98df-11e9-843b-313967f9bfdd.png)

**Comment by mozbhearsum** [comment]
> Never mind I think I get it. The "Delete Scheduled Change" button in the pop-up is the same as the "Schedule For Deletion" button that we see in the rules view.

Not exactly.

In the first dialog, the "Delete Scheduled Change" button effectively cancels a pending change (regardless of whether it will create a new rule, modify an existing one, or delete an existing one. This is done with a DELETE to /scheduled_changes/rules/:sc_id (note that sc_id is different than rule_id -- scheduled changes have their own sc_id (their primary key), as well as the rule_id that they will modify, which is not part of the primary key of a scheduled change).

The "Schedule for Deletion" button creates a new scheduled change that will delete the Rule. This is done with a POST to /scheduled_changes/rules.

Does that make sense?

**Comment by helfi92** [comment]
That makes perfect sense! The "Delete" threw me off I guess. Maybe we could rename to something like "Revoke" or "Cancel". Anyways, thanks for making this clear to me :)

**Comment by mozbhearsum** [comment]
> That makes perfect sense! The "Delete" threw me off I guess. Maybe we could rename to something like "Revoke" or "Cancel". Anyways, thanks for making this clear to me :)

"Cancel" sounds like a good replacement to me.

**Comment by mozbhearsum** [comment]
https://github.com/mozilla/balrog/pull/950 will add support to the backend for retrieving scheduled changes to rules/releases by rule_id/release name.
