### ISSUE TITLE
Make the delete operation more obvious in the rules view

### ISSUE THREAD

**Issue by helfi92** [mozilla-frontend-infra/balrog-ui#39]
We should try to make the delete operation more obvious by either re-fetching the list or animating the delete.

**Comment by helfi92** [comment]
In order to make the delete operation more obvious, I think we could rely on a confirmation box for the feedback.

**Comment by mozbhearsum** [comment]
I think this was addressed in #47?

**Comment by helfi92** [comment]
> I think this was addressed in #47?

The delete operation was done but I don't think we make it clear to the user. A feedback via a simple snackbar https://material-ui.com/components/snackbars/#snackbars might be useful to have for better UX.

**Comment by mozbhearsum** [comment]
Oh, I see. Sorry, I thought this was an old issue.
