### ISSUE TITLE
cannot type custom names into Required Signoffs product/channel field

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-frontend-infra/balrog-ui#43]
If I try to type something that's not in the suggestions, the field ends up blank when I leave focus.

**Comment by helfi92** [comment]
Do we ever want to allow users to write something that isn't in the suggestions?

**Comment by mozbhearsum** [comment]
Yeah, this might be something we do when a new product or channel is created. (It's also faster to simply type sometimes than to select from the suggestions.)

**Comment by helfi92** [comment]
> (It's also faster to simply type sometimes than to select from the suggestions.)

I believe the current state allows you to write it manually as long as when you navigate away from it (e.g., press tab), it matches a string in the suggestions.

**Comment by mozbhearsum** [comment]
> > (It's also faster to simply type sometimes than to select from the suggestions.)
> 
> I believe the current state allows you to write it manually as long as when you navigate away from it (e.g., press tab), it matches a string in the suggestions.

This doesn't work for me. If I type, then navigate away (whether by keyboard or mouse), the text is lost.

**Comment by mozbhearsum** [comment]
I dug into this a bit more today and it looks like this may be a known bug in downshift: https://github.com/downshift-js/downshift/issues/714
