### ISSUE TITLE
Menu takes time to show up when long list of options (e.g., rules view)

### ISSUE THREAD

**Issue by helfi92** [mozilla-frontend-infra/balrog-ui#54]
From https://github.com/mozilla-frontend-infra/balrog-ui/pull/49:

> Changing the product/channel filter in the dropdown has just enough of a delay to be annoying, maybe ~500ms.

Let's investigate why this is happening.

**Comment by helfi92** [comment]
@mozbhearsum Is this still an issue for you?

**Comment by mozbhearsum** [comment]
It either got better or I got used to it :). Let's close this unless it comes up again.
