### ISSUE TITLE
Page doesn't render if authentication fails

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-frontend-infra/balrog-ui#55]
When I tried loading my local UI this morning I got a blank page, and a 400 from auth0.

The auth issues looks like #16, but the lack of rendering is most likely fallout from #48.

**Comment by helfi92** [comment]
Any idea how I could reproduce this issue?

**Comment by mozbhearsum** [comment]
I tried a few things and was unable to anymore. Maybe it got fixed with some other recent changes.
