### ISSUE TITLE
implement view for showing releases

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-frontend-infra/balrog-ui#58]

**Comment by helfi92** [comment]
Planning to work on this next. As always, let me know if I should focus my energy elsewhere for now.

**Comment by mozbhearsum** [comment]
Makes sense to me. Once this, #63, and #64 are done we'll have all of the major pieces for an MVP and it'll be easier to find all of the small issues that we need to resolve before cutting over.

**Comment by helfi92** [comment]
> Once this, #63, and #64 are done we'll have all of the major pieces for an MVP and it'll be easier to find all of the small issues that we need to resolve before cutting over.

Exciting!! 🎉

**Comment by helfi92** [comment]
Resolved in https://github.com/mozilla-frontend-infra/balrog-ui/commit/7b61f42ee99ccb6a32db2c8a838d4a29c8bb87dc.
