### ISSUE TITLE
UI for rules history

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-frontend-infra/balrog-ui#63]
At minimum, we need to be able to view history by rule id. It would be even better if we could look at the entire Rules table at a specific point in time, though (this would probably need some backend support).

**Comment by helfi92** [comment]
![Screen Shot 2019-07-22 at 11 03 55 AM](https://user-images.githubusercontent.com/3766511/61643241-72920e80-ac70-11e9-88c7-1316a8d79735.png)
