### ISSUE TITLE
UI for releases history

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-frontend-infra/balrog-ui#64]
A view that shows changes to a Release over time should be enough here. Being able to diff between Release revisions is important for understandability.

Unlike other parts of Balrog, Release history is stored in GCS, and it must be queried for directly there (not through the backend). This is done through queries like, eg: https://www.googleapis.com/storage/v1/b/balrog-prod-nightly-history-v1/o?prefix=Firefox-mozilla-central-nightly-latest/&delimeter=/.

**Comment by helfi92** [comment]
I can try to work on one of the history views next. I will be a bit busy with Taskcluster this week so progress will be slow but fwiw, that's what I'm planning to tackle next. Let me know if I should focus my energy elsewhere.

**Comment by helfi92** [comment]
I noticed that the Product/Channel filter of a rule revision is always empty. Is this always the case?

_Example: https://localhost:8010/rules/306_

<img width="1200" alt="Screen Shot 2019-07-18 at 6 54 36 PM" src="https://user-images.githubusercontent.com/3766511/61497473-834f3580-a98d-11e9-9a7f-2319424635c6.png">

**Comment by mozbhearsum** [comment]
It doesn't really make sense to show it at all in the context of a single Rules history. Looks like a bug to me!

**Comment by helfi92** [comment]
We could probably use a similar UI to the rule revisions view.

**Comment by helfi92** [comment]
I'm currently trying to think of a possible layout for this view. The view in the old site looks like

![Screen Shot 2019-08-06 at 12 32 55 PM](https://user-images.githubusercontent.com/3766511/62558163-7adc7300-b846-11e9-8d7c-7a0a9d5683ef.png)


It would probably be good to make the layout similar to the roles revisions view. 2 questions come to mind:

1. Does "View Diff" show the diff with the current release? Would it be good if we use a similar layout to the rules revisions view (https://github.com/mozilla-frontend-infra/balrog-ui/pull/102#issue-299921309?

2. "View Data" shows the JSON representation of the release. Would it make sense to show a release card instead via the `ReleaseCard` component. We would probably need to introduce a `readOnly` prop similar to `RuleCard` to make sure action buttons are hidden.

**Comment by mozbhearsum** [comment]
> Does "View Diff" show the diff with the current release? Would it be good if we use a similar layout to the rules revisions view (#102 (comment)?

"View Diff" actually diffs against the previous revision. I think using a similar layout to the Rules history would be great. Having the ability to diff between arbitrary revisions of a Release would be useful in some cases.

> "View Data" shows the JSON representation of the release. Would it make sense to show a release card instead via the ReleaseCard component. We would probably need to introduce a readOnly prop similar to RuleCard to make sure action buttons are hidden.

I don't think showing a ReleaseCard is terribly useful actually. The only data in a Release row are name, version, product, and the JSON data. The user already knows the name of the Release they are working with when entering the history view, and version and product are rarely useful, generally part of the name (in addition to being their own fields), and almost never change. This means that the JSON data is really the only thing we care about in this view. As long as users can obtain a diff, and easily see the full version of the data at a revision, that should address all use cases.
