### ISSUE TITLE
figure out content security policy story for new UI

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-frontend-infra/balrog-ui#65]
In the current Balrog UI we implement a CSP with a <meta> tag (https://github.com/mozilla/balrog/blob/master/ui/app/pages/index.us#L8). We'll need something to replace this in the new UI. We're planning to deploy it as a static site in S3 so we may end up doing it elsewhere (eg: https://aws.amazon.com/blogs/networking-and-content-delivery/adding-http-security-headers-using-lambdaedge-and-amazon-cloudfront/)

**Comment by mozbhearsum** [comment]
I had a brief look into this today, and it looks like we'll need something like:
```
default-src 'none';
script-src 'self' 'unsafe-eval';
img-src 'self' https://*.gravatar.com https://*.githubusercontent.com https://i1.wp.com;
style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
font-src https://fonts.gstatic.com;
connect-src 'self' https://localhost:8010 "/>
```

A few notes:
* I'm not sure why we need `unsafe-inline` for `style-src`. We should probably try to root this out and drop it.
* I think the `unsafe-eval` is only needed for local development (because of webpack/hotreload), so hopefully we don't this in stage/prod.
* Similarly, I think `self` is only needed in `connect-src` for local dev.
* The actual host needed for the backend will differ on environment. Because of this, I think it's probably going to make sense to have this managed in Amazon, not a `meta` tag. See https://aws.amazon.com/blogs/networking-and-content-delivery/adding-http-security-headers-using-lambdaedge-and-amazon-cloudfront/.

**Comment by helfi92** [comment]
As a reference, here's what we use in:

* taskcluster - https://github.com/taskcluster/taskcluster/blob/master/static.json
* codetribute - https://github.com/mozilla-frontend-infra/codetribute/blob/master/netlify.toml

**Comment by helfi92** [comment]
@mozbhearsum Should we consider this resolved?

**Comment by mozbhearsum** [comment]
Yeah, sounds good. We can open a follow-up if anything new comes up.
