### ISSUE TITLE
implement UI for emergency shutoff mechanism

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-frontend-infra/balrog-ui#66]
Balrog has an "Emergency Shutoff" mechanism wherein someone can send a POST to /api/emergency_shutoff with a product and channel, and updates for those will be immediately stopped (regardless of whether or not changes to that product+channel normally require signoff). We'll need new UI for this.

As noted above, shutting off is a single request. Re-enabling updates requires signoff if the given product+channel has Required Signoffs specified.

**Comment by mozbhearsum** [comment]
I was working on implementing some of this today and after adding a new Card to show a SignoffSummary, it started to feel awkward to put other aspects of the Emergency Shutoff information elsewhere. If there's going to be a card, it feels like we may as well always use it to show information and place buttons on. What do you think about the following:
Updates are shutoff, and not scheduled to be enabled:
![image](https://user-images.githubusercontent.com/49649/63974081-1a71d780-ca7a-11e9-8270-d6029d58e3b8.png)

Updates are shutoff, and scheduled to be enabled:
![image](https://user-images.githubusercontent.com/49649/63974097-28275d00-ca7a-11e9-8918-8381a4a53898.png)

(Obviously there's some styling work to do.)

The other advantage of this approach is that we can drop the entire component onto the home page if we like.

Apologies for the change of direction here, this seems obvious in retrospect :upside_down_face:

**Comment by mozbhearsum** [comment]
Hm, we'll actually still need to use the SpeedDial for the "Shutoff Updates" button at the very least, now that I think about it...

**Comment by helfi92** [comment]
Looks good to me.

**Comment by mozbhearsum** [comment]
Fixed in #184
