### ISSUE TITLE
improve display of pending rule inserts

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-frontend-infra/balrog-ui#71]
They currently show up only with a diff section:
![image](https://user-images.githubusercontent.com/49649/60901633-48862880-a23c-11e9-9c4d-e01a8693c7a9.png)

Maybe we can show them in a card, and have an indicator that it is still scheduled?

**Comment by helfi92** [comment]
That's a good idea. Exposing the scheduled ID might also be a good idea so we can deep link for example.

**Comment by mozbhearsum** [comment]
It would be good to give them an anchor, too, so we can link back to them when making changes to them.

**Comment by helfi92** [comment]
Agreed. I started working on this a bit. Just need to find the time to finish this.
