### ISSUE TITLE
make it easy to see all pending signoffs for a role

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-frontend-infra/balrog-ui#88]
This is not necessary for an MVP, but a use case that has come up a few times is the ability to see what is what changes are awaiting signoff by a particular Role. This can be helpful during release days when we're trying to make sure everything that needs to be, is signed off on.

I can see this having a few possible forms:
* A user specific view, that shows the logged in user anything they could potentially sign off on.
* A role specific view, that shows anything that a given role could potentially sign off on.
* Something integrated into the existing Rule, Release, Required Signoffs, and User views, which somehow makes it very obvious which items are awaiting signoff.

Or it could be something entirely different.

**Comment by mozbhearsum** [comment]
As a relatively simple thing to solve the immediate use case of 'what-in-the-heck-needs-signoff', how about a drop down like:
![image](https://user-images.githubusercontent.com/49649/65360205-f878fa00-dbcc-11e9-82a1-7c82a7d5e285.png)

I'm tentatively calling this "Display Mode", and would additionally filter the list based on the selected item.

cc'ing a few folks that have may have opinions @lizzard, @lundjordan, @rehandalal.

I still think something else may be useful, but I want to make sure we address the immediate need quickly.

**Comment by lizzard** [comment]
That looks good to me!

**Comment by helfi92** [comment]
Instead of a dropdown, how do you feel about simply adding a switch toggle component with a label along the lines of "Show rules requiring signoff"? If it's important for a user to sometimes view rules that have no signoffs required, then a dropdown like the image above sounds good to me.

**Comment by helfi92** [comment]
> a name for the toggle that wouldn't cause confusion

Perhaps "Filter by rules requiring signoff" :)

**Comment by lundjordan** [comment]
> Perhaps "Filter by rules requiring signoff" :)

A filter or toggle wfm. so long as it was also in the URL so I can share it quickly.

**Comment by mozbhearsum** [comment]
I did a bit of hacking on this in https://github.com/mozilla-frontend-infra/balrog-ui/compare/master...mozbhearsum:display-mode-rules?expand=1. It looks like I'm going to be busy with other things for a week or two though, so I won't be able to finish it up immediately.

**Comment by helfi92** [comment]
I may have some time this week to look into this. I'll be in PTO the week after. I'll see if I can continue on this, of course if that's alright with you.
