### ISSUE TITLE
set page titles

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-frontend-infra/balrog-ui#89]
Right now, there's no document.title set. It would be good to have it set to the same thing as `title` in the `Dashboard` (to help people distinguish if they have multiple tabs open).

**Comment by helfi92** [comment]
It used to be defined but not anymore ever since we started using a manual template. To handle the default title, we just need to add `<title>Balrog Admin</title>` in the header section of `index.html`. We can also use https://github.com/nfl/react-helmet to make sure it updates in each view.
