### ISSUE TITLE
Cross-origin request blocked

### ISSUE THREAD

**Issue by helfi92** [mozilla-frontend-infra/balrog-ui#95]
![Screen Shot 2019-07-18 at 3 20 50 PM](https://user-images.githubusercontent.com/3766511/61485665-b08ceb00-a96f-11e9-86c7-1d207e20e0f6.png)

**Comment by helfi92** [comment]
@mozbhearsum Are you able to replicate?

**Comment by mozbhearsum** [comment]
Yeah. It looks to me like it's caused by a 404. I see URLs such as `https://localhost:8010/api/rules/history/?changed_by=bhearsum%40mozilla.com&timestamp_from=2019-07-18T16%3A01%3A00.000Z&timestamp_to=2019-07-19T18%3A10%3A00.000Z` being used - the trailing slash on the path is problematic.

**Comment by helfi92** [comment]
I see. Could you give an example of a URL that would work?

**Comment by mozbhearsum** [comment]
https://localhost:8010/api/rules/history?changed_by=bhearsum%40mozilla.com&timestamp_from=0&timestamp_to=99999999999999999999999 (the timestamp format is unix epoch, to the millisecond).

**Comment by mozbhearsum** [comment]
Can we close this now?

**Comment by helfi92** [comment]
Indeed.
