### ISSUE TITLE
jaws & mig64 values change unexpectedly

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-frontend-infra/balrog-ui#98]
While testing something unrelated, I noticed that jaws and mig64 tried to change from null -> false when I only meant to change another field:
![image](https://user-images.githubusercontent.com/49649/61560844-70933a00-aa3b-11e9-9357-bae7dfb7f233.png)

It looks like the frontend translates false into null at some point.

**Comment by helfi92** [comment]
Good catch. We should fix that.

**Comment by helfi92** [comment]
I believe this was fixed.
