### ISSUE TITLE
rule list should return to the last filtered product+channel after editing a rule

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-frontend-infra/balrog-ui#99]
With a workflow like:
1) Go to /rules?product=Firefox&channel=release
2) Click "Update"
3) Edit a rule and get redirected back to /rules

...we end up redirecting back to a page that doesn't have a product/channel filter applied, which is jarring, and not usually what a user would want.

A few ideas for addressing this, although there's probably others:
- Store the last filtered value and always apply that (we do this in the old UI). This would mean that an initial load of /rules would automatically filter in most cases.
- Redirect back to /rules with a product/channel filter applied based on what's in the rule that was just edited. We'd have to be careful to strip away wildcards if we did this.
- Forward the current filter to the rule edit page, and use that when redirecting back.

**Comment by helfi92** [comment]
One idea that comes to mind is to redirect to `/rules#ruleId=<rule-id>`. If we want to maintain the same query, we could look at the history stack and grab the query and append it `/rules?foo=bar#ruleId=<rule-id>`. The latter is probably extra when the list of rules are sorted lexicographically.

**Comment by mozbhearsum** [comment]
> One idea that comes to mind is to redirect to `/rules#ruleId=<rule-id>`. If we want to maintain the same query, we could look at the history stack and grab the query and append it `/rules?foo=bar#ruleId=<rule-id>`. The latter is probably extra when the list of rules are sorted lexicographically.

This sounds good to me.

**Comment by helfi92** [comment]
Updating a rule currently redirects to the rule page with the page scrolled to the updated rule since we provide the hash. Should we consider this resolved?

**Comment by mozbhearsum** [comment]
> Updating a rule currently redirects to the rule page with the page scrolled to the updated rule since we provide the hash. Should we consider this resolved?

The Rules page is almost never useful without a product and channel filtered applied, so at the very least we should redirect back to whatever the previous filter was.

This raises the question of what to do on first load though, (eg: a request to /rules without any explicit filter). The resulting page is never going to be what somebody wants - the very first thing they'll do is apply a filter. This is why we store the last applied filter in localStorage in the old UI.

**Comment by helfi92** [comment]
> The Rules page is almost never useful without a product and channel filtered applied, so at the very least we should redirect back to whatever the previous filter was.

That would be doable with the state feature that react-router provides without having to store the value in localStorage.

> This raises the question of what to do on first load though, (eg: a request to /rules without any explicit filter). The resulting page is never going to be what somebody wants - the very first thing they'll do is apply a filter. This is why we store the last applied filter in localStorage in the old UI.

If we add a search input similar to the releases view, then `/rules` will probably be what a user always wants. They will always have the option to use the filter if the search input is not enough. Thoughts?

**Comment by mozbhearsum** [comment]
> If we add a search input similar to the releases view, then /rules will probably be what a user always wants. They will always have the option to use the filter if the search input is not enough. Thoughts?

What are you thinking the search would look like? The drop down takes the place of the search function for most use cases, I think.

**Comment by mozbhearsum** [comment]
Fixed in #175
